# Build order: avr-binutils -> avr-gcc -> avr-libc
name       : avr-binutils
version    : 2.32
release    : 4
source     :
    - https://ftp.gnu.org/gnu/binutils/binutils-2.32.tar.xz : 0ab6c55dd86a92ed561972ba15b9b70a8b9f75557f896446c82e8b36e473ee04
license    : GPL-3.0-or-later
summary    : The GNU Embedded Binutils for AVR
component  : programming
description: |
    A set of programs to assemble and manipulate binary and object files for the AVR architecture
environment: |
    export TARGET=avr
    export PREFIX=/usr/share/$TARGET
setup      : |
    %patch -Np0 < $pkgfiles/avr-size.patch

    ./configure \
        --build=%HOST% \
        --target=$TARGET \
        --prefix=$PREFIX \
        --enable-ld=default \
        --enable-gold \
        --enable-plugins \
        --enable-threads \
        --enable-shared \
        --with-pic \
        --disable-werror \
        --disable-multilib
    %make configure-host
build      : |
    %make
install    : |
    %make_install

    # Remove binaries that conflict with host binutils
    for bin in ar as nm objcopy objdump ranlib strip readelf; do
        rm -f $installdir$PREFIX/bin/$bin
    done

    # Rename info files with avr prefix
    for info in as bfd binutils gprof ld; do
        mv $installdir$PREFIX/share/info/$info.info $installdir$PREFIX/share/info/avr-$info.info
    done

    # Remove unnecessary files
    rm -r $installdir$PREFIX/share

    # Install profile.d script which adds arm toolchain to path
    install -D -m 00644 $pkgfiles/50-avr-toolchain-path.sh $installdir/usr/share/defaults/etc/profile.d/50-avr-toolchain-path.sh
